#include "Entity.h"

Entity::Entity() {
	//initialize private variables with the default values below
	_hp = 0;
	_attack = 0;
	_defence = 0;
	_xPos = 0;
	_yPos = 0;
}

Entity::Entity(int hp, int attack, int defence) {
	//initialize private variables with the parameter values
	_hp = hp;
	_attack = attack;
	_defence = defence;
	_xPos = 0;
	_yPos = 0;
}

int Entity::attack() {
	//return the damage that will be given based on the number generated by the RNG 
	srand((unsigned int)time(NULL));
	return rand() % _attack + 0;

}


void Entity::accept(Visitor& v) {
	v.Visit(*this);
}

void Entity::setPos(int xPos, int yPos) {
	_xPos = xPos;
	_yPos = yPos;
}

void Entity::setHp(int value) {
	_hp = value;
}

void Entity::setAttack(int value) {
	_attack = value;
}

void Entity::setDefence(int value) {
	_defence = value;
}

void Entity::getPos(int& xPos, int& yPos) {
	xPos = _xPos;
	yPos = _yPos;
}

int Entity::getHp() const {
	return _hp;
}

int Entity::getAttack() const {
	return _attack;
}

int Entity::getDefence() const {
	return _defence;
}
